export type HomeLocale = "id" | "en";

export const programs = [
  { name: "Business Academy", id: "Pelatihan entrepreneurship yang sistematis, praktis, dan dekat dengan tantangan usaha nyata.", en: "Structured, practical entrepreneurship training grounded in real business challenges." },
  { name: "Pitching & Access to Capital", id: "Mempersiapkan pengusaha muda menyusun pitch, memahami kebutuhan modal, dan membangun kesiapan pendanaan.", en: "Preparing young entrepreneurs to pitch, understand capital needs, and become funding-ready." },
  { name: "Networking & Business Expo", id: "Ruang temu mahasiswa, pengusaha, pemerintah, komunitas, dan jaringan bisnis untuk membuka peluang kolaborasi.", en: "A meeting point for students, entrepreneurs, government, communities, and business networks." },
  { name: "100 Pengusaha Muda", id: "Program pembentukan pengusaha mahasiswa dengan jalur belajar, validasi, dan pengembangan usaha.", en: "A pathway to create student entrepreneurs through learning, validation, and venture development." },
  { name: "LinggauPreneur Summit", id: "Forum entrepreneurship, networking, dan business leadership untuk ekosistem muda di Linggau Raya.", en: "An entrepreneurship, networking, and business leadership forum for the Greater Linggau ecosystem." },
  { name: "Business Visit", id: "Belajar langsung dari operasional bisnis, pemilik usaha, dan praktik lapangan.", en: "Learning directly from business operations, founders, and field practice." },
  { name: "Entrepreneur Talk", id: "Percakapan terbuka dengan entrepreneur dan profesional yang sudah melewati fase membangun bisnis.", en: "Open conversations with entrepreneurs and professionals who have built businesses firsthand." },
  { name: "Business Incubator", id: "Pendampingan untuk mempertajam model bisnis, pasar, operasi, dan pertumbuhan usaha anggota.", en: "Support to sharpen member ventures across business model, market, operations, and growth." },
  { name: "Investment Club", id: "Edukasi investasi dan pasar modal untuk membangun literasi keuangan pengusaha muda.", en: "Investment and capital-market education to strengthen financial literacy among young entrepreneurs." }
] as const;

export const ecosystem = [
  { title: "HIPMI PT", id: "Pusat koordinasi, identitas, dan jejaring organisasi.", en: "The coordination, identity, and network hub." },
  { title: "Members", id: "Talenta mahasiswa yang belajar, membangun, dan berkolaborasi.", en: "Students who learn, build, and collaborate." },
  { title: "Businesses", id: "Usaha anggota menjadi laboratorium bisnis yang nyata.", en: "Member ventures become real-world business laboratories." },
  { title: "Pasar UMKM", id: "Lapisan commerce untuk mempertemukan produk dengan pasar.", en: "The commerce layer connecting products with customers." },
  { title: "Business Academy", id: "Peningkatan kompetensi melalui kurikulum entrepreneurship.", en: "Capability building through entrepreneurship learning." },
  { title: "Mentorship", id: "Akses pengalaman dari praktisi dan pengusaha senior.", en: "Access to experience from practitioners and senior entrepreneurs." },
  { title: "Partnership", id: "Kolaborasi dengan kampus, pemerintah, komunitas, dan bisnis.", en: "Collaboration with campus, government, communities, and business." },
  { title: "Funding", id: "Kesiapan menuju akses modal dan peluang investasi yang relevan.", en: "Readiness for relevant capital and investment opportunities." },
  { title: "Growth", id: "Tujuan akhirnya: usaha yang lebih sehat, kompetitif, dan berdampak.", en: "The end goal: healthier, more competitive, higher-impact ventures." }
] as const;

export const stories = [
  { image: "/media/hero-pelantikan.webp", tagId: "Organisasi", tagEn: "Organization", titleId: "Pelantikan Akbar HIPMI PT Kampus se-Linggau Raya 2026", titleEn: "2026 Greater Linggau HIPMI PT Grand Inauguration" },
  { image: "/media/mentorship-bpc.webp", tagId: "Mentorship", tagEn: "Mentorship", titleId: "Sharing bersama pengusaha senior BPC HIPMI Lubuklinggau", titleEn: "Mentorship session with senior BPC HIPMI Lubuklinggau entrepreneurs" },
  { image: "/media/sinergi-pemkot.webp", tagId: "Kolaborasi", tagEn: "Collaboration", titleId: "Menjalin sinergi strategis bersama Pemerintah Kota Lubuklinggau", titleEn: "Building strategic synergy with the Lubuklinggau City Government" }
] as const;

export const homeCopy = {
  id: {
    heroEyebrow: "Official Digital Headquarters · Lubuklinggau",
    heroTitle: "Membangun generasi pengusaha muda kampus.",
    heroBody: "HIPMI PT UIN Al Azhaar adalah ruang kolaborasi, pembelajaran, networking, dan pengembangan bisnis bagi mahasiswa yang ingin membangun masa depan melalui entrepreneurship.",
    heroPrimary: "Jelajahi program",
    heroSecondary: "Gabung jaringan",
    snapshotLabel: "Snapshot organisasi",
    aboutEyebrow: "Lebih dari organisasi",
    aboutTitle: "Sebuah ekosistem entrepreneurship yang bekerja dari kampus ke pasar.",
    aboutBody: "Kami menghubungkan mahasiswa dengan pengetahuan, mentor, jaringan bisnis, ruang kolaborasi, dan akses pengembangan usaha. Setiap program dirancang untuk membawa anggota dari minat menjadi kemampuan, dari kemampuan menjadi usaha, dan dari usaha menuju pertumbuhan.",
    aboutAside: "Visi 2026/2027",
    programsEyebrow: "Program unggulan",
    programsTitle: "Bukan agenda seremonial. Program dirancang untuk menghasilkan kemampuan yang bisa dipakai.",
    ecosystemEyebrow: "Business ecosystem",
    ecosystemTitle: "Satu jaringan. Banyak jalur pertumbuhan.",
    ecosystemBody: "Klik setiap lapisan untuk melihat perannya dalam perjalanan anggota dari komunitas menuju pertumbuhan bisnis.",
    businessTitle: "Dari komunitas ke pasar.",
    businessBody: "Website resmi berfungsi sebagai institutional hub. Pasar UMKM menjadi commerce layer. Business Directory akan menjadi katalog usaha anggota. Arsitektur ini sengaja dipisahkan agar setiap produk digital dapat berkembang tanpa saling mengunci.",
    impactEyebrow: "Impact baseline",
    impactTitle: "Mengukur sebelum mengklaim.",
    impactBody: "Kami tidak menampilkan angka dampak yang belum tercatat. Baseline di bawah adalah data organisasi yang sudah terverifikasi; metrik outcome akan masuk saat sistem pencatatan resmi berjalan.",
    agendaEyebrow: "Upcoming",
    agendaTitle: "Agenda publik berikutnya belum diumumkan.",
    agendaBody: "Pengumuman event, pembukaan registrasi, dan kegiatan kolaborasi akan dipublikasikan melalui kanal resmi HIPMI PT.",
    agendaCta: "Pantau Instagram",
    storiesEyebrow: "Field notes",
    storiesTitle: "Aktivitas nyata, bukan stok foto.",
    partnerEyebrow: "Strategic collaboration",
    partnerTitle: "Kolaborasi lintas kampus, bisnis, dan pemerintah.",
    partnerBody: "HIPMI PT membangun koneksi yang relevan untuk memperluas akses belajar, jaringan, pasar, mentorship, dan peluang pengembangan pengusaha muda.",
    partnerCta: "Ajukan kolaborasi",
    leadershipEyebrow: "Leadership",
    leadershipTitle: "Kepemimpinan yang bertugas membuka akses, bukan sekadar memegang jabatan.",
    leadershipBody: "Periode 2026/2027 diarahkan untuk membangun organisasi yang rapi, aktif, terukur, dan semakin dekat dengan ekosistem bisnis Lubuklinggau.",
    galleryEyebrow: "Documentation",
    galleryTitle: "Ekosistem yang terlihat karena benar-benar bergerak.",
    joinEyebrow: "Join the network",
    joinTitle: "Masuk ke jaringan. Bangun kemampuan. Mulai usaha. Tumbuh bersama.",
    joinBody: "HIPMI PT terbuka bagi mahasiswa UIN Al Azhaar yang ingin belajar entrepreneurship, membangun usaha, memperluas jaringan, dan menciptakan dampak ekonomi yang nyata.",
    joinCta: "Hubungi HIPMI PT"
  },
  en: {
    heroEyebrow: "Official Digital Headquarters · Lubuklinggau",
    heroTitle: "Building a generation of young campus entrepreneurs.",
    heroBody: "HIPMI PT UIN Al Azhaar is a space for collaboration, learning, networking, and business development for students building their future through entrepreneurship.",
    heroPrimary: "Explore programs",
    heroSecondary: "Join the network",
    snapshotLabel: "Organization snapshot",
    aboutEyebrow: "More than an organization",
    aboutTitle: "An entrepreneurship ecosystem that works from campus to market.",
    aboutBody: "We connect students with knowledge, mentors, business networks, collaboration spaces, and venture-development access. Every program is designed to move members from interest to capability, capability to business, and business to growth.",
    aboutAside: "Vision 2026/2027",
    programsEyebrow: "Flagship programs",
    programsTitle: "Not ceremonial programming. Each initiative is designed to build capability people can use.",
    ecosystemEyebrow: "Business ecosystem",
    ecosystemTitle: "One network. Multiple paths to growth.",
    ecosystemBody: "Open each layer to see its role in moving members from community to business growth.",
    businessTitle: "From community to market.",
    businessBody: "The official website acts as the institutional hub. Pasar UMKM is the commerce layer. Business Directory will become the member venture catalogue. These products are intentionally separated so each can scale without locking the others.",
    impactEyebrow: "Impact baseline",
    impactTitle: "Measure before making claims.",
    impactBody: "We do not display impact numbers that have not been recorded. The baseline below contains verified organizational data; outcome metrics will follow once official tracking is active.",
    agendaEyebrow: "Upcoming",
    agendaTitle: "The next public agenda has not been announced yet.",
    agendaBody: "Events, registrations, and collaboration activities will be announced through HIPMI PT's official channels.",
    agendaCta: "Follow Instagram",
    storiesEyebrow: "Field notes",
    storiesTitle: "Real activity, not stock photography.",
    partnerEyebrow: "Strategic collaboration",
    partnerTitle: "Collaboration across campus, business, and government.",
    partnerBody: "HIPMI PT builds relevant connections to widen access to learning, networks, markets, mentorship, and growth opportunities for young entrepreneurs.",
    partnerCta: "Propose collaboration",
    leadershipEyebrow: "Leadership",
    leadershipTitle: "Leadership exists to open access, not simply hold titles.",
    leadershipBody: "The 2026/2027 term is focused on building an organized, active, measurable institution that is increasingly connected to Lubuklinggau's business ecosystem.",
    galleryEyebrow: "Documentation",
    galleryTitle: "An ecosystem you can see because it is actually moving.",
    joinEyebrow: "Join the network",
    joinTitle: "Enter the network. Build capability. Start a venture. Grow together.",
    joinBody: "HIPMI PT is open to UIN Al Azhaar students who want to learn entrepreneurship, build ventures, expand networks, and create real economic impact.",
    joinCta: "Contact HIPMI PT"
  }
} as const;
